FROM python:3.12-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Add repository code

WORKDIR /opt/dagster/app

COPY . .

# Run dagster gRPC server on port 5000

EXPOSE 5000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "5000", "-f", "definitions.py"]