FROM python:3.12-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker\
    pandas \
    psycopg2_binary \
    PyYAML \
    requests \
    requests_cache \
    setuptools \
    SQLAlchemy \
    tenacity

# Add repository code

WORKDIR /opt/dagster/app

COPY . .

# Run dagster gRPC server on port 5000

EXPOSE 5000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "5000", "-f", "definitions.py"]